Import('env')

# Include dir for users of this lib
env.Append(CPPPATH=Glob('include'))

# Set QT5DIR and PKG_CONFIG_PATH
env['QT5DIR'] = '/home/cody/Qt/5.12.0/gcc_64'
env['ENV']['PKG_CONFIG_PATH'] = '/home/cody/Qt/5.12.0/gcc_64/lib/pkgconfig'

# Add qt5 tool
env.Tool('qt5')
env.EnableQt5Modules([
    'QtGui',
    'QtCore',
    'QtWidgets'
    ])

localEnv = env.Clone()

# Generate Form files
localEnv.Uic5(Glob('*.ui'))

# Create the library
localEnv.Library('qtgui', Glob('*.cpp'))