import os

Import('env')

env['QT5DIR'] = '/home/cody/Qt/5.12.0/gcc_64'
env['ENV']['PKG_CONFIG_PATH'] = '/home/cody/Qt/5.12.0/gcc_64/lib/pkgconfig'

# Add qt5 tool
env.Tool('qt5')
env.EnableQt5Modules([
    'QtGui',
    'QtCore',
    'QtWidgets'
])

sources = [
    'main.cpp',
    Glob('image/*.cpp'),
    Glob('noise/*.cpp'),
    Glob('qt/*.cpp'),
]

env.Program('#/bin/simplex_noise', sources)
